# 헤비 유저가 소유한 장소
SELECT A.ID, A.NAME, A.HOST_ID
FROM PLACES A, (SELECT B.HOST_ID, COUNT(B.HOST_ID) FROM PLACES B
    GROUP BY B.HOST_ID HAVING COUNT(B.HOST_ID)>1) B
WHERE A.HOST_ID = B.HOST_ID
ORDER BY ID;
