-- 루시와 엘라 찾기
SELECT ANIMAL_ID, NAME, SEX_UPON_INTAKE 
FROM ANIMAL_INS 
WHERE NAME IN ('Lucy', 'Ella', 'Pickle', 'Rogan', 'Sabrina', 'Mitty') ORDER BY ANIMAL_ID


  
-- 이름에 el이 들어가는 동물 찾기
SELECT ANIMAL_ID, NAME 
FROM ANIMAL_INS 
WHERE NAME LIKE '%el%' AND ANIMAL_TYPE = 'Dog' ORDER BY NAME


  
-- 중성화 여부 판단하기
SELECT ANIMAL_ID, NAME, IF(SEX_UPON_INTAKE LIKE '%NEUTERED%' OR SEX_UPON_INTAKE LIKE '%SPAYED%','O','X') AS '중성화'
FROM ANIMAL_INS 
ORDER BY ANIMAL_ID


  
-- 오랜 기간 보호한 동물(2)
SELECT ANIMAL_OUTS.ANIMAL_ID, ANIMAL_OUTS.NAME 
FROM ANIMAL_OUTS, ANIMAL_INS
WHERE ANIMAL_OUTS.ANIMAL_ID = ANIMAL_INS.ANIMAL_ID
ORDER BY TIMESTAMPDIFF(MINUTE, ANIMAL_INS.DATETIME, ANIMAL_OUTS.DATETIME) DESC LIMIT 2

  
-- DATETIME에서 DATE로 형 변환
SELECT ANIMAL_ID, NAME, DATE_FORMAT(DATETIME, '%Y-%m-%d') AS 날짜 
FROM ANIMAL_INS
ORDER BY ANIMAL_ID


  
-- 조건별로 분류하여 주문상태 출력하기
SELECT
    ORDER_ID
    , PRODUCT_ID
    , DATE_FORMAT(OUT_DATE, '%Y-%m-%d') AS OUT_DATE
    , CASE
        WHEN DATEDIFF('2022-05-01', OUT_DATE) >= 0 THEN '출고완료'
        WHEN DATEDIFF('2022-05-01', OUT_DATE) < 0 THEN '출고대기'
        ELSE '출고미정'
    END AS '출고여부'
FROM FOOD_ORDER 
ORDER BY ORDER_ID


  
-- 대여 기록이 존재하는 자동차 리스트 구하기
SELECT
    distinct crcc.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR crcc
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY crcrh
    ON crcc.CAR_ID = crcrh.CAR_ID
        AND MONTH(crcrh.START_DATE) = 10
WHERE 
    crcc.CAR_TYPE = '세단'
ORDER BY crcc.CAR_ID DESC


  
-- 조건에 맞는 사용자 정보 조회하기
SELECT
    ugb.WRITER_ID -- ugu.USER_ID
    , ugu.NICKNAME
    , CONCAT(ugu.CITY, ' ', ugu.STREET_ADDRESS1, ' ', ugu.STREET_ADDRESS2) AS '전체주소'
    , CONCAT(SUBSTRING(TLNO, 1, 3), '-', SUBSTRING(TLNO, 4, 4), '-', SUBSTRING(TLNO, 8, 4))AS '전화번호'
FROM USED_GOODS_BOARD ugb
    JOIN USED_GOODS_USER ugu
        ON ugb.WRITER_ID = ugu.USER_ID
GROUP BY ugb.WRITER_ID
HAVING COUNT(ugb.WRITER_ID) >= 3
ORDER BY ugb.WRITER_ID DESC


  
-- 조회수가 가장 많은 중고거래 게시판의 첨부파일 조회하기
SELECT
    CONCAT('/home/grep/src/', ugf.BOARD_ID, '/', ugf.FILE_ID, ugf.FILE_NAME, ugf.FILE_EXT)AS FILE_PATH
FROM
    USED_GOODS_FILE ugf
    JOIN USED_GOODS_BOARD ugb
    ON ugf.BOARD_ID = ugb.BOARD_ID
        AND ugb.VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
ORDER BY FILE_PATH DESC


  
-- 취소되지 않은 진료 예약 조회하기
SELECT
    APPOINTMENT.APNT_NO
    ,PATIENT.PT_NAME
    ,PATIENT.PT_NO
    ,DOCTOR.MCDP_CD
    ,DOCTOR.DR_NAME
    ,APPOINTMENT.APNT_YMD
FROM APPOINTMENT 
    JOIN (SELECT * FROM PATIENT) PATIENT 
        ON APPOINTMENT.PT_NO = PATIENT.PT_NO
    JOIN (SELECT * FROM DOCTOR) DOCTOR 
        ON APPOINTMENT.MDDR_ID = DOCTOR.DR_ID
WHERE 
    DATE_FORMAT(APPOINTMENT.APNT_YMD, '%Y-%m-%d') = '2022-04-13'
    AND APPOINTMENT.APNT_CNCL_YN = 'N'
    AND APPOINTMENT.MCDP_CD = 'CS'
ORDER BY APPOINTMENT.APNT_YMD


  
-- 자동차 대여 기록 별 대여 금액 구하기
SELECT
    crcrh.HISTORY_ID
    ,CASE
        WHEN DATEDIFF(END_DATE, START_DATE)+1 < 7 -- 7일 미만
            THEN ROUND((DATEDIFF(END_DATE, START_DATE)+1) * crcc.DAILY_FEE, 0) 
        WHEN DATEDIFF(END_DATE, START_DATE)+1 >= 7 AND DATEDIFF(END_DATE, START_DATE)+1 < 30 -- 7일 이상 (30일 미만)
            THEN ROUND((DATEDIFF(END_DATE, START_DATE)+1) * (1-(SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = '트럭' AND DURATION_TYPE = '7일 이상')/100) * crcc.DAILY_FEE, 0) 
        WHEN DATEDIFF(END_DATE, START_DATE)+1 >= 30 AND DATEDIFF(END_DATE, START_DATE)+1 < 90 -- 30일 이상 (90일 미만)
            THEN ROUND((DATEDIFF(END_DATE, START_DATE)+1) * (1-(SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = '트럭' AND DURATION_TYPE = '30일 이상')/100) * crcc.DAILY_FEE, 0) 
        WHEN DATEDIFF(END_DATE, START_DATE)+1 >= 90 -- 90일 이상
            THEN ROUND((DATEDIFF(END_DATE, START_DATE)+1) * (1-(SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = '트럭' AND DURATION_TYPE = '90일 이상')/100) * crcc.DAILY_FEE, 0) 
    END AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY crcrh
    JOIN (
        SELECT CAR_ID, DAILY_FEE
        FROM CAR_RENTAL_COMPANY_CAR
        WHERE CAR_TYPE = '트럭'
    ) crcc
        ON crcc.CAR_ID = crcrh.CAR_ID
ORDER BY FEE DESC, crcrh.HISTORY_ID DESC
